.TH vzmpipe 8 "October 2009" "OpenVZ"

.SH NAME
vzmpipe - Utility that's used as shell for special user created for
Containers migration purposes

.SH SYNOPSIS
.TP
.B /usr/sbin/vzmpipe

.SH DESCRIPTION
You DON'T need to use it directly. It is used as shell for special
user.

.SH COPYRIGHT
Copyright (c) 2001-2016, Parallels IP Holdings GmbH. All rights reserved.
