.TH vzmpipe 8 "October 2009" "@PRODUCT_NAME_SHORT@"

.SH NAME
vzmpipe - Utility that's used as shell for special user created for
Containers migration purposes

.SH SYNOPSIS
.TP
.B /usr/sbin/vzmpipe

.SH DESCRIPTION
You DON'T need to use it directly. It is used as shell for special
user.

.SH COPYRIGHT
Copyright (c) 2001-2017, Parallels International GmbH. All rights reserved.
Copyright (c) 2017-2019 Virtuozzo International GmbH. All rights reserved.
